project:
  type: book
  output-dir: _book

book:
  title: "Toxicology in Art"
  subtitle: "Poisoning and poisons in history and painting"
  author: "Nik Danilov"
  date: "2025"
  chapters:
    - index.qmd
    - preface.qmd
    - chapters/Sophonisba.qmd

format:
  pdf:
    documentclass: book
    fontsize: 12pt
    mainfont: "Libertinus Serif"
    monofont: "Inconsolata"
    geometry:
      - top=3cm
      - bottom=3cm
      - left=3cm
      - right=3cm
    include-in-header: includes/preamble.tex

