project:
  type: book
  output-dir: _book

book:
  title: "Toxicology in Art"
  subtitle: "Poisoning and poisons in history and painting"
  author: "Nik Danilov"
  date: "2025"
  chapters:
    - index.qmd
    - preface.qmd
    - chapters/Sophonisba.qmd

format:
  pdf:
    pdf-engine: xelatex
    documentclass: scrbook
    papersize: a4
    fontsize: 14pt
    mainfont: "Times New Roman"
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=2.5cm
      - right=2.5cm
    titlepage: true
    titlepage-geometry: "top=4cm,bottom=3cm,left=3cm,right=3cm"
    titlepage-rule-color: "gray"
    titlepage-rule-height: 1
    titlepage-footer: |
      Haifa, 2025
    toc: true
    number-sections: true
    colorlinks: true
