project:
  type: book
  output-dir: _book

book:
  title: "Toxicology in Art"
  author: "Nik Danilov"
  date: "2025-10-25"
  chapters:
    - index.qmd
    - preface.qmd
    - part: "Fabules"
      chapters:
        - chapters/Sophonisba.qmd

  page-navigation: true

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  pdf:
    documentclass: scrbook
