[build]
  command = "mkdir -p $HOME/.local && curl -L https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.57/quarto-1.5.57-linux-amd64.tar.gz | tar -xz -C $HOME/.local --strip-components=1 && export PATH=$HOME/.local/bin:$PATH && quarto render"
  publish = "_book"

[build.environment]
  QUARTO_VERSION = "1.5.57"

[context.production.environment]
  HUGO_VERSION = "0.111.3"

[context.deploy-preview]
  command = "quarto render"
