name: Render Quarto PDF

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.5.57"

      - name: Install TinyTeX and required fonts
        run: |
          quarto install tinytex --no-prompt
          echo "$HOME/.TinyTeX/bin/x86_64-linux" >> $GITHUB_PATH
          # Install TeX Gyre and other basic fonts
          tlmgr install collection-fontsrecommended
          tlmgr install tex-gyre

      - name: Verify installation
        run: |
          quarto check install
          quarto --version
          which xelatex

      - name: Render PDF
        run: quarto render --to pdf

      - name: Commit rendered PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _book/*.pdf || true
          git commit -m "Auto-update rendered PDF" || echo "No changes to commit"
          git push
